#Test generated by the 'rails generate controller' scaffold
require 'test_helper'

class StaticPagesControllerTest < ActionDispatch::IntegrationTest

  test "should get home" do
    get static_pages_home_url #get /static_pages/home URL
    assert_response :success #verify successful result
  end

  test "should get help" do
    get static_pages_help_url #get /static_pages/help URL
    assert_response :success #verify successful result
  end

#':success' represents HTTP status code '200 OK', meaning that the server sent back the appropriate status code.

#Test Driven Development - use a failing test to write code that will pass.

  test "should get about" do
    get static_pages_about_url
    assert_response :success
  end

#This test will fail until the 'About' static page, route and controller are created.

end
